# Generated by Django 2.0.5 on 2018-05-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=300)),
                ('sender_email_address', models.CharField(max_length=320)),
                ('recipient_name', models.CharField(blank=True, max_length=300)),
                ('recipient_email_address', models.CharField(max_length=320)),
                ('reply_name', models.CharField(blank=True, max_length=300)),
                ('reply_email_address', models.CharField(blank=True, max_length=320)),
                ('subject', models.CharField(max_length=300)),
                ('plain_content', models.TextField(blank=True)),
                ('html_content', models.TextField(blank=True)),
                ('event_description', models.CharField(blank=True, max_length=100)),
                ('message_id', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('send_after', models.DateTimeField(blank=True, null=True)),
                ('sending_status', models.PositiveSmallIntegerField(choices=[(0, 'Unsent'), (1, 'Sending'), (2, 'Failed to queue'), (3, 'Sent'), (4, 'To be removed from the queue'), (5, 'Removed from the queue'), (6, 'Failed to send')], default=0)),
                ('resend_count', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedEmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=300)),
                ('sender_email_address', models.CharField(max_length=320)),
                ('recipient_name', models.CharField(blank=True, max_length=300)),
                ('recipient_email_address', models.CharField(max_length=320)),
                ('date', models.DateTimeField()),
                ('subject', models.TextField(blank=True)),
                ('plain_content', models.TextField()),
                ('html_content', models.TextField()),
                ('headers', models.ManyToManyField(to='emails.EmailHeader')),
            ],
        ),
    ]
